task/urls.py
from django.urls import path

from task.views import index, TaskDetailView,\
    TaskCreateView, TaskUpdateView, TaskDeleteView,\
    TagListView, TagDetailView, TagUpdateView, TagDeleteView,\
    TagCreateView, task_done_changing, TaskListView


urlpatterns = [
    path("", index, name="index"),

    path("tasks/", TaskListView.as_view(), name="task_list"),
    path("task/<int:pk>/done/", task_done_changing, name="task_done"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task_detail"),
    path("tasks/create/", TaskCreateView.as_view(), name="task_create"),
    path("tasks/<int:pk>/update", TaskUpdateView.as_view(), name="task_update"),
    path("tasks/<int:pk>/delete", TaskDeleteView.as_view(), name="task_delete"),
    path("tags/", TagListView.as_view(), name="tag_list"),
    path("tags/<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag_update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("tags/create/", TagCreateView.as_view(), name="tag_create"),
]

app_name = "task"

task_tegs/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("task.urls", namespace="task")),

    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

task/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    date_of_creation = models.DateTimeField(auto_now=True)
    deadline = models.DateField(null=True, blank=True)
    done = models.BooleanField()
    tag = models.ManyToManyField(Tag, related_name="tasks")

    def __str__(self):
        return self.content

task/forms.py
from django import forms

from task.models import Task

task/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic

from task.models import Tag, Task


def index(request):
    num_tags = Tag.objects.count()
    num_tasks = Task.objects.count()

    context = {
        "num_tags": num_tags,
        "num_tasks": num_tasks,
    }

    return render(request, "task/index.html", context=context)


class TaskListView(generic.ListView):
    model = Task
    queryset = Task.objects.all().prefetch_related("tag")


def task_done_changing(request, pk):
    task = Task.objects.get(pk=pk)

    task.done = not task.done
    task.save()

    return redirect("task:task_list")


class TaskDetailView(generic.DetailView):
    model = Task


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("task:task_list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("task:task_list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("task:task_list")


class TagListView(generic.ListView):
    model = Tag
    paginate_by = 5


class TagDetailView(generic.DetailView):
    model = Tag


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("task:tag_list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("task:tag_list")


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("task:tag_list")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Tasks & Tags: {% block title %}Home{% endblock %}</title>
  <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">

  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

            {% block pagination %}
                {% include "includes/pagination.html" %}
            {% endblock %}

        </div>
    </div>
</div>
</body>
</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page={{ page_obj.previous_page_number }}" class="page-link"><</a>
      </li>
    {% endif %} 
    <li>
      <span class="page-link">{{ page_obj.number }} of {{ page_obj.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page={{ page_obj.next_pagee_number }}" class="page-link">></a>
      </li>
    {% endif %}
  </ul>
{% endif %} 

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url "task:index" %}">Home</a></li>
  {% if "/tasks/" not in request.path_info %}
    <li class="list-group-item"><a href="{% url "task:task_list" %}">Tasks</a></li>
  {% endif %}
  {% if "/tags/" not in request.path_info %}
    <li class="list-group-item"><a href="{% url "task:tag_list" %}">Tags</a></li>
  {% endif %}
</ul>

templates/task/index.html
{% extends "base.html" %}

{% block title %}
 Home Page
{% endblock %}

{% block content %}
  <h1>Tasks & Tags</h1>

  <hr>

  <p>we have: {{ num_tags }} tags and {{ num_tasks }} tasks.</p>
{% endblock %}

templates/task/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Confirm delete tag</h1>
  <p>Are you sure what you want to delete the tag?</p>

    <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/task/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
{% endblock %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Tag</h1>

  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/task/tag_list.html
{% extends "base.html" %}

{% block title %}
{% endblock %}

{% block content %}
  <h1>
    Tags
    <a href="{% url "task:tag_create" %}" class="btn btn-primary" style="float: right">Create</a>
  </h1>
  <table class="table">
    <tr>
      <th>Name</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>
    {% for tag in tag_list %}
      <tr>
        <td>{{ tag.name }}</td>
        <td><a href="{% url "task:tag_update" pk=tag.id %}" class="btn btn-info">Update</a></td>
        <td><a href="{% url "task:tag_delete" pk=tag.id %}" class="btn btn-danger">Delete</a></td>
      </tr>
    {% endfor %}
  </table>
{% endblock %}

templates/task/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Confirm delete task</h1>
  <p>Are you sure what you want to delete the task?</p>

    <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/task/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
{% endblock %}

{% block content %}

  <h1>{{ object|yesno:"Update,Create" }} Task</h1>

  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>

{% endblock %}

templates/task/task_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
  Tasks
{% endblock %}

{% block content %}
  <h1>
    TODO list
    <a href="{% url "task:task_create" %}" class="btn btn-primary" style="float: right">Create</a>
  </h1>
  {% for task in task_list %}
    <hr>
    <h3>
      {{ task.content }}: {% if task.done == False %}Not Done{% else %}Done{% endif %}
      {% if task.done %}
        <a href="{% url "task:task_done" pk=task.id %}" class="btn btn-danger">Cancel</a>
        {% else %}
        <a href="{% url "task:task_done" pk=task.id %}" class="btn btn-primary">Complete</a>
      {% endif %}
    </h3>

    <p>Created: {{ task.date_of_creation }}{% if task.deadline is not null %}, Deadline: {{ task.deadline }}{% endif %} </p>
    <p>Tags:
      {% if task.tag.all %}
       {% for tag in task.tag.all %}{{ tag.name }} {% endfor %}
        {% else %}
         None
      {% endif %}
    </p>

    <p>
      <a href="{% url "task:task_update" pk=task.id %}">Update</a>
      <a href="{% url "task:task_delete" pk=task.id %}">Delete</a>
    </p>
  {% endfor %}

{% endblock %}